### ISSUE TITLE
The input size of dla34_deform_576_768.onnx is not really 576x768

### ISSUE THREAD

**Issue by mamadouDembele** [Owen-Liuyuxuan/ros2_vision_inference#4]
Hi,
First of all, thank you for providing the pre-trained models for 3D detection and segmentation. When loading the model dla34_deform_576_768.onnx on [netron](https://netron.app/) the input size of the model displayed is 384x1280. Do you have a dla34_deform of size 576x768?

Best

**Comment by Owen-Liuyuxuan** [comment]
Oh sorry, actually there is, and there are actually multiple 576x768 and 384x1280 models on the servers... I made mistakes when I manually tagging them the names..

**Comment by Owen-Liuyuxuan** [comment]
https://github.com/Owen-Liuyuxuan/ros2_vision_inference/releases/tag/v1.1.1  (It's also available in the new README)

I added both models. Very sorry for making this mistakes.

**Comment by mamadouDembele** [comment]
Thank you very much for your response. I have started to test the 3d detection models of the readme on a sample kitti image. The results obtained are as follows: 

-  mono3d_yolox_576_768.onnx
![yolox_2d](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/0e6be1ce-ac8b-422b-8233-85aeb022b3b1)

![yolox_3d](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/8768eb07-3b97-44c5-b681-7f69aa262ced)
- dla34_deform_576_768.onnx
![dla34_576_768_2d](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/16b6cff3-e239-49df-b48f-8eb08fe445fd)

![dla34_576_768_3d](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/872e1db8-fd0e-4164-b30a-a6c13bd45d5a)

- dla34_deform_384_1280.onnx
![dla34_384_1280_2d](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/ca06b354-f791-4318-886a-43a17aee28ef)

![dla34_384_1280](https://github.com/Owen-Liuyuxuan/ros2_vision_inference/assets/57793779/2b915f44-2c92-43fa-b174-6d216cef8402)

As you can see, I've tested the three models on the readme: mono3d_yolox_576_768.onnx, dla34_deform_384_1280.onnx and dla34_deform_576_768.onnx. For each model, I display the results of the 2d detection and the results of the 3d detection (with the top view and the associated ground-truth). The dla34_deform_x_y.onnx seems to be better than the mono3d_yolox_576_768.onnx. The dla34_deform_384_1280.onnx model is more accurate than the dla34_deform_576_768.onnx model. This is because the ratio between the H/W = 375/1242 input image and that of the 384/1280 model input are fairly close. 

In the coming days, I plan to test the models on images from our autonomous shuttles and compare the results with the lidar segmentation. I'll share the results if I can.

Best

**Comment by Owen-Liuyuxuan** [comment]
Great, that is what I have expected. 

1. The 384/1280 models are mainly tailored for KITTI datasets. 
2. DLA34 is a significantly larger backbone than YOLOX. 

So the result makes sense to me.
